export const texts = {
  id: {
    settingsGroup: "PENGATURAN",
    helpGroup: "BANTUAN",
    infoGroup: "INFORMASI",
    chat: "Obrolan",
    notif: "Notifikasi",
    privacy: "Pengaturan Privasi",
    blockedUsers: "Pengguna Diblokir",
    language: "Bahasa / Language",
    accountSettings: "Pengaturan Akun",
    chatSettingsTitle: "Pengaturan Obrolan",
    notifSettingsTitle: "Pengaturan Notifikasi",
    privacySettingsTitle: "Pengaturan Privasi",
    blockedUsersTitle: "Pengguna Diblokir",
    helpTitle: "Pusat Bantuan",
    rulesTitle: "Peraturan Komunitas",
    policyTitle: "Kebijakan",
    valuesTitle: "Nilai Kami",
    infoTitle: "Informasi Aplikasi",
    deleteTitle: "Penghapusan Akun",
    deleteWarning: "Penghapusan akun bersifat permanen.",
    deleteButton: "Hapus Akun",
    logoutTitle: "Keluar",
    logoutPrompt: "Apakah Anda yakin ingin keluar?",
    logoutButton: "Keluar",
    saveChat: "SIMPAN PENGATURAN CHAT",
    savePreferences: "SIMPAN PREFERENSI",
    savePrivacy: "SIMPAN PRIVASI",
    unblock: "Buka Blokir",
    blockedCount: "ANDA MEMBLOKIR 3 PENGGUNA / TOKO",
    chatNotif: "Notifikasi Chat",
    chatNotifDesc: "Terima pemberitahuan pesan baru",
    statusOnline: "Tampilkan Status Online",
    statusOnlineDesc: "Izinkan orang lain melihat saat Anda online",
    enterSend: "Kirim dengan Enter",
    enterSendDesc: "Gunakan tombol Enter untuk mengirim pesan",
    autoReply: "Auto Reply",
    autoReplyDesc: "Kirim pesan otomatis saat Anda tidak aktif",
    promo: "Promo & Diskon",
    promoDesc: "Dapatkan info promo spesial harian",
    orderUpdate: "Update Pesanan",
    orderUpdateDesc: "Status pengiriman & konfirmasi",
    newsletter: "Newsletter",
    newsletterDesc: "Berita terhangat dari kami",
    access: "Akses Akun",
    accessDesc: "Notifikasi saat ada perangkat baru masuk",
    privateAccount: "Akun Privat",
    privateAccountDesc: "Hanya teman yang bisa melihat aktivitas Anda",
    hideHistory: "Sembunyikan Riwayat Belanja",
    hideHistoryDesc: "Review Anda tidak ditampilkan di profil",
    biometric: "Otentikasi Sidik Jari",
    biometricDesc: "Gunakan biometrik saat membuka aplikasi",
    personalizedAds: "Iklan Terpersonalisasi",
    personalizedAdsDesc: "Rekomendasi berdasarkan minat Anda",
    blockedListTitle: "Pengguna yang diblokir",
    unblockButton: "Buka Blokir",
    blockedFooter: "ANDA MEMBLOKIR 3 PENGGUNA / TOKO",
    helpText: "Hubungi customer service jika membutuhkan bantuan.",
    rulesText: "Peraturan komunitas akan ditampilkan di sini.",
    policyText: "Kebijakan privasi aplikasi.",
    valuesText: "Nilai dan budaya perusahaan.",
    infoText: "Versi aplikasi 1.0.0",
    searchPlaceholder: "Cari produk favoritmu...",
    searchButton: "Cari",
    loginButton: "Masuk",
    registerButton: "Daftar",
    profileMenuProfile: "Profil Saya",
    profileMenuOrders: "Pesanan Saya",
    profileMenuSettings: "Pengaturan",
  },
  "en-uk": {
    settingsGroup: "SETTINGS",
    helpGroup: "HELP",
    infoGroup: "INFORMATION",
    chat: "Chat",
    notif: "Notifications",
    privacy: "Privacy Settings",
    blockedUsers: "Blocked Users",
    language: "Language",
    accountSettings: "Account Settings",
    chatSettingsTitle: "Chat Settings",
    notifSettingsTitle: "Notification Settings",
    privacySettingsTitle: "Privacy Settings",
    blockedUsersTitle: "Blocked Users",
    helpTitle: "Help Center",
    rulesTitle: "Community Rules",
    policyTitle: "Policy",
    valuesTitle: "Our Values",
    infoTitle: "App Information",
    deleteTitle: "Delete Account",
    deleteWarning: "Account deletion is permanent.",
    deleteButton: "Delete Account",
    logoutTitle: "Logout",
    logoutPrompt: "Are you sure you want to log out?",
    logoutButton: "Logout",
    saveChat: "SAVE CHAT SETTINGS",
    savePreferences: "SAVE PREFERENCES",
    savePrivacy: "SAVE PRIVACY",
    unblock: "Unblock",
    blockedCount: "YOU HAVE BLOCKED 3 USERS / STORES",
    chatNotif: "Chat Notifications",
    chatNotifDesc: "Receive notifications for new messages",
    statusOnline: "Show Online Status",
    statusOnlineDesc: "Allow others to see when you are online",
    enterSend: "Send with Enter",
    enterSendDesc: "Use the Enter key to send messages",
    autoReply: "Auto Reply",
    autoReplyDesc: "Send automatic messages when you're unavailable",
    promo: "Promo & Discounts",
    promoDesc: "Get daily special promo info",
    orderUpdate: "Order Updates",
    orderUpdateDesc: "Shipping status & confirmations",
    newsletter: "Newsletter",
    newsletterDesc: "The latest news from us",
    access: "Account Access",
    accessDesc: "Notifications when a new device logs in",
    privateAccount: "Private Account",
    privateAccountDesc: "Only friends can see your activity",
    hideHistory: "Hide Purchase History",
    hideHistoryDesc: "Your reviews will not show on your profile",
    biometric: "Fingerprint Authentication",
    biometricDesc: "Use biometrics to unlock the app",
    personalizedAds: "Personalized Ads",
    personalizedAdsDesc: "Recommendations based on your interests",
    blockedListTitle: "Blocked users",
    unblockButton: "Unblock",
    blockedFooter: "YOU HAVE BLOCKED 3 USERS / STORES",
    helpText: "Contact customer service if you need help.",
    rulesText: "Community rules will be shown here.",
    policyText: "App privacy policy.",
    valuesText: "Company values and culture.",
    infoText: "App version 1.0.0",
    searchPlaceholder: "Search favorite products...",
    searchButton: "Search",
    loginButton: "Login",
    registerButton: "Register",
    profileMenuProfile: "My Profile",
    profileMenuOrders: "My Orders",
    profileMenuSettings: "Settings",
  },
  "en-us": {
    settingsGroup: "SETTINGS",
    helpGroup: "HELP",
    infoGroup: "INFORMATION",
    chat: "Chat",
    notif: "Notifications",
    privacy: "Privacy Settings",
    blockedUsers: "Blocked Users",
    language: "Language",
    accountSettings: "Account Settings",
    chatSettingsTitle: "Chat Settings",
    notifSettingsTitle: "Notification Settings",
    privacySettingsTitle: "Privacy Settings",
    blockedUsersTitle: "Blocked Users",
    helpTitle: "Help Center",
    rulesTitle: "Community Rules",
    policyTitle: "Policy",
    valuesTitle: "Our Values",
    infoTitle: "App Information",
    deleteTitle: "Delete Account",
    deleteWarning: "Account deletion is permanent.",
    deleteButton: "Delete Account",
    logoutTitle: "Logout",
    logoutPrompt: "Are you sure you want to log out?",
    logoutButton: "Logout",
    saveChat: "SAVE CHAT SETTINGS",
    savePreferences: "SAVE PREFERENCES",
    savePrivacy: "SAVE PRIVACY",
    unblock: "Unblock",
    blockedCount: "YOU HAVE BLOCKED 3 USERS / STORES",
    chatNotif: "Chat Notifications",
    chatNotifDesc: "Receive notifications for new messages",
    statusOnline: "Show Online Status",
    statusOnlineDesc: "Allow others to see when you are online",
    enterSend: "Send with Enter",
    enterSendDesc: "Use the Enter key to send messages",
    autoReply: "Auto Reply",
    autoReplyDesc: "Send automatic messages when you're unavailable",
    promo: "Promo & Discounts",
    promoDesc: "Get daily special promo info",
    orderUpdate: "Order Updates",
    orderUpdateDesc: "Shipping status & confirmations",
    newsletter: "Newsletter",
    newsletterDesc: "The latest news from us",
    access: "Account Access",
    accessDesc: "Notifications when a new device logs in",
    privateAccount: "Private Account",
    privateAccountDesc: "Only friends can see your activity",
    hideHistory: "Hide Purchase History",
    hideHistoryDesc: "Your reviews will not show on your profile",
    biometric: "Fingerprint Authentication",
    biometricDesc: "Use biometrics to unlock the app",
    personalizedAds: "Personalized Ads",
    personalizedAdsDesc: "Recommendations based on your interests",
    blockedListTitle: "Blocked users",
    unblockButton: "Unblock",
    blockedFooter: "YOU HAVE BLOCKED 3 USERS / STORES",
    helpText: "Contact customer service if you need help.",
    rulesText: "Community rules will be shown here.",
    policyText: "App privacy policy.",
    valuesText: "Company values and culture.",
    infoText: "App version 1.0.0",
  },
  zh: {
    settingsGroup: "设置",
    helpGroup: "帮助",
    infoGroup: "信息",
    chat: "聊天",
    notif: "通知",
    privacy: "隐私设置",
    blockedUsers: "已屏蔽用户",
    language: "语言",
    accountSettings: "账户设置",
    chatSettingsTitle: "聊天设置",
    notifSettingsTitle: "通知设置",
    privacySettingsTitle: "隐私设置",
    blockedUsersTitle: "已屏蔽用户",
    helpTitle: "帮助中心",
    rulesTitle: "社区规则",
    policyTitle: "政策",
    valuesTitle: "我们的价值观",
    infoTitle: "应用信息",
    deleteTitle: "删除账户",
    deleteWarning: "账户删除是永久性的。",
    deleteButton: "删除账户",
    logoutTitle: "登出",
    logoutPrompt: "您确定要退出吗？",
    logoutButton: "退出",
    saveChat: "保存聊天设置",
    savePreferences: "保存偏好",
    savePrivacy: "保存隐私",
    unblock: "解除屏蔽",
    blockedCount: "您已屏蔽 3 个用户/店铺",
    chatNotif: "聊天通知",
    chatNotifDesc: "接收新消息通知",
    statusOnline: "显示在线状态",
    statusOnlineDesc: "允许他人查看您何时在线",
    enterSend: "回车发送",
    enterSendDesc: "使用回车键发送消息",
    autoReply: "自动回复",
    autoReplyDesc: "当您不可用时发送自动消息",
    promo: "促销与折扣",
    promoDesc: "获取每日特价促销信息",
    orderUpdate: "订单更新",
    orderUpdateDesc: "运输状态与确认",
    newsletter: "新闻通讯",
    newsletterDesc: "来自我们的最新消息",
    access: "账户访问",
    accessDesc: "新设备登录时通知您",
    privateAccount: "私人账户",
    privateAccountDesc: "只有好友可以看到您的活动",
    hideHistory: "隐藏购买历史",
    hideHistoryDesc: "您的评论不会显示在个人资料中",
    biometric: "指纹验证",
    biometricDesc: "使用生物识别解锁应用",
    personalizedAds: "个性化广告",
    personalizedAdsDesc: "根据您的兴趣推荐",
    blockedListTitle: "已屏蔽用户",
    unblockButton: "解除屏蔽",
    blockedFooter: "您已屏蔽 3 个用户/店铺",
    helpText: "如需帮助，请联系客服。",
    rulesText: "社区规则将在此显示。",
    policyText: "应用隐私政策。",
    valuesText: "公司价值观和文化。",
    infoText: "应用版本 1.0.0",
    searchPlaceholder: "搜索你喜欢的商品...",
    searchButton: "搜索",
    loginButton: "登录",
    registerButton: "注册",
    profileMenuProfile: "我的资料",
    profileMenuOrders: "我的订单",
    profileMenuSettings: "设置",
  },
};
